### ISSUE TITLE
[BUG]: ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 514946) of binary: 

### ISSUE THREAD

**Issue by Haoran1234567** [hpcaitech/ColossalAI#3556]
### 🐛 Describe the bug

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 514946) of binary: 

[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1807582 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1809346 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1805522 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1804789 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1807703 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1805474 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27962, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1804809 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 514949 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 514946) of binary: /home/qihaoran/.conda/envs/coati_test/bin/python
Traceback (most recent call last):
  File "/home/qihaoran/.conda/envs/coati_test/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/home/qihaoran/.conda/envs/coati_test/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/qihaoran/.conda/envs/coati_test/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/qihaoran/.conda/envs/coati_test/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/qihaoran/.conda/envs/coati_test/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/qihaoran/.conda/envs/coati_test/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train_sft.py FAILED
-------------------------------------------------------
Failures:
[1]:
  time      : 2023-04-13_10:28:15
  host      : gpu8
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 514947)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 514947
[2]:
  time      : 2023-04-13_10:28:15
  host      : gpu8
  rank      : 4 (local_rank: 4)
  exitcode  : -6 (pid: 514950)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 514950
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-13_10:28:15
  host      : gpu8
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 514946)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 514946

### Environment

Colossal-AI version: 0.2.8
PyTorch version: 1.13.0
System CUDA version: 11.7
CUDA version required by PyTorch: 11.7

**Comment by Haoran1234567** [comment]
When I train train_sft with very small training data instructino_wild, it can run normally. When I increase some data, this happens, but the increased data is not much.

i use 3090 8*24g

**Comment by Haoran1234567** [comment]
Here is my run script：
torchrun --standalone --nproc_per_node=8 train_sft.py \
    --pretrain $PRETRAIN \
    --model 'llama' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path $SAVE_PATH \
    --dataset $DATASET \
    --batch_size 2 \
    --accimulation_steps 16 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 3

and i set 
elif args.strategy == 'colossalai_zero2':
        strategy = ColossalAIStrategy(stage=2, placement_policy='cpu'),because when placement_policy='cuda',OOM error

**Comment by xienan0326** [comment]
meet the same problem, have you resolved it 
![image](https://user-images.githubusercontent.com/38122102/232370707-57607d6d-3b83-4715-bfce-8f4c3dc00a73.png)

**Comment by Camille7777** [comment]
> meet the same problem, have you resolved it ![image](https://user-images.githubusercontent.com/38122102/232370707-57607d6d-3b83-4715-bfce-8f4c3dc00a73.png)

@xienan0326 can you provide more information about this error? Actually your exitcode is different from his/her. :)

**Comment by xienan0326** [comment]
> > meet the same problem, have you resolved it ![image](https://user-images.githubusercontent.com/38122102/232370707-57607d6d-3b83-4715-bfce-8f4c3dc00a73.png)
> 
> @xienan0326 can you provide more information about this error? Actually your exitcode is different from his/her. :)
detail, plz

Map:  96%|██████████████████████████████████████████████████WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5620 closing signal SIGTERM             
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5622 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 1 (pid: 5621) of binary: /usr/bin/python3.10
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
finetune.py FAILED
----------------------------------------------------
Failures:
[1]:
  time      : 2023-04-18_08:32:53
  host      : e27e4dca5000
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 5623)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 5623
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-18_08:32:53
  host      : e27e4dca5000
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 5621)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 5621
====================================================

**Comment by Camille7777** [comment]
> 

hii, have you check with the memory usage during the training? It is likely cpu runs out of memory. You can try allocating more main memory and run it again.

**Comment by Camille7777** [comment]
> > > meet the same problem, have you resolved it ![image](https://user-images.githubusercontent.com/38122102/232370707-57607d6d-3b83-4715-bfce-8f4c3dc00a73.png)
> > 
> > 
> > @xienan0326 can you provide more information about this error? Actually your exitcode is different from his/her. :)
> > detail, plz
> 
> # Map: 96%|██████████████████████████████████████████████████WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5620 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5622 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 1 (pid: 5621) of binary: /usr/bin/python3.10
> Traceback (most recent call last):
> File "/usr/local/bin/torchrun", line 8, in
> sys.exit(main())
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> return f(*args, **kwargs)
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
> run(args)
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
> elastic_launch(
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## finetune.py FAILED
> ## Failures:
> [1]:
> time : 2023-04-18_08:32:53
> host : e27e4dca5000
> rank : 3 (local_rank: 3)
> exitcode : -7 (pid: 5623)
> error_file: <N/A>
> traceback : Signal 7 (SIGBUS) received by PID 5623
> # Root Cause (first observed failure):
> [0]:
> time : 2023-04-18_08:32:53
> host : e27e4dca5000
> rank : 1 (local_rank: 1)
> exitcode : -7 (pid: 5621)
> error_file: <N/A>
> traceback : Signal 7 (SIGBUS) received by PID 5621

hii, have you check with the memory usage during the training? It is likely cpu runs out of memory. You can try allocating more main memory and run it again.

**Comment by xienan0326** [comment]
0%|                                                                                  | 0/21 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1318 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 1315) of binary: /usr/bin/python3.10
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
fastchat/train/train_mem.py FAILED
----------------------------------------------------
Failures:
[1]:
  time      : 2023-04-20_11:37:39
  host      : ab00e35df170
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 1316)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 1316
[2]:
  time      : 2023-04-20_11:37:39
  host      : ab00e35df170
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 1317)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 1317
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-20_11:37:39
  host      : ab00e35df170
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 1315)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 1315
====================================================

**Comment by Camille7777** [comment]
> > > > > meet the same problem, have you resolved it ![image](https://user-images.githubusercontent.com/38122102/232370707-57607d6d-3b83-4715-bfce-8f4c3dc00a73.png)
> > > > 
> > > > 
> > > > @xienan0326 can you provide more information about this error? Actually your exitcode is different from his/her. :)
> > > > detail, plz
> > > 
> > > 
> > > # Map: 96%|██████████████████████████████████████████████████WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5620 closing signal SIGTERM
> > > WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5622 closing signal SIGTERM
> > > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 1 (pid: 5621) of binary: /usr/bin/python3.10
> > > Traceback (most recent call last):
> > > File "/usr/local/bin/torchrun", line 8, in
> > > sys.exit(main())
> > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> > > return f(*args, **kwargs)
> > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
> > > run(args)
> > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
> > > elastic_launch(
> > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in **call**
> > > return launch_agent(self._config, self._entrypoint, list(args))
> > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
> > > raise ChildFailedError(
> > > torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> > > ## finetune.py FAILED
> > > ## Failures:
> > > [1]:
> > > time : 2023-04-18_08:32:53
> > > host : e27e4dca5000
> > > rank : 3 (local_rank: 3)
> > > exitcode : -7 (pid: 5623)
> > > error_file: <N/A>
> > > traceback : Signal 7 (SIGBUS) received by PID 5623
> > > # Root Cause (first observed failure):
> > > [0]:
> > > time : 2023-04-18_08:32:53
> > > host : e27e4dca5000
> > > rank : 1 (local_rank: 1)
> > > exitcode : -7 (pid: 5621)
> > > error_file: <N/A>
> > > traceback : Signal 7 (SIGBUS) received by PID 5621
> > 
> > 
> > hii, have you check with the memory usage during the training? It is likely cpu runs out of memory. You can try allocating more main memory and run it again.
> > It doesn't seem like a memory issue, the peak is 90g
> > ![image](https://user-images.githubusercontent.com/38122102/233356267-9c4bc1d3-dd4e-4ec2-9957-5390a156e2c0.png)

Hi, @xienan0326 can you provide your running command for this?

**Comment by xienan0326** [comment]
> > > > > > meet the same problem, have you resolved it ![image](https://user-images.githubusercontent.com/38122102/232370707-57607d6d-3b83-4715-bfce-8f4c3dc00a73.png)
> > > > > 
> > > > > 
> > > > > @xienan0326 can you provide more information about this error? Actually your exitcode is different from his/her. :)
> > > > > detail, plz
> > > > 
> > > > 
> > > > # Map: 96%|██████████████████████████████████████████████████WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5620 closing signal SIGTERM
> > > > WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5622 closing signal SIGTERM
> > > > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 1 (pid: 5621) of binary: /usr/bin/python3.10
> > > > Traceback (most recent call last):
> > > > File "/usr/local/bin/torchrun", line 8, in
> > > > sys.exit(main())
> > > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> > > > return f(*args, **kwargs)
> > > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
> > > > run(args)
> > > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
> > > > elastic_launch(
> > > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in **call**
> > > > return launch_agent(self._config, self._entrypoint, list(args))
> > > > File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
> > > > raise ChildFailedError(
> > > > torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> > > > ## finetune.py FAILED
> > > > ## Failures:
> > > > [1]:
> > > > time : 2023-04-18_08:32:53
> > > > host : e27e4dca5000
> > > > rank : 3 (local_rank: 3)
> > > > exitcode : -7 (pid: 5623)
> > > > error_file: <N/A>
> > > > traceback : Signal 7 (SIGBUS) received by PID 5623
> > > > # Root Cause (first observed failure):
> > > > [0]:
> > > > time : 2023-04-18_08:32:53
> > > > host : e27e4dca5000
> > > > rank : 1 (local_rank: 1)
> > > > exitcode : -7 (pid: 5621)
> > > > error_file: <N/A>
> > > > traceback : Signal 7 (SIGBUS) received by PID 5621
> > > 
> > > 
> > > hii, have you check with the memory usage during the training? It is likely cpu runs out of memory. You can try allocating more main memory and run it again.
> > > It doesn't seem like a memory issue, the peak is 90g
> > > ![image](https://user-images.githubusercontent.com/38122102/233356267-9c4bc1d3-dd4e-4ec2-9957-5390a156e2c0.png)
> 
> Hi, @xienan0326 can you provide your running command for this?
Thank you.This bug has been fixed. by "--shm-size="1g"". but，i got Another bug. very sad, plz help me
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: driver shutting down
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f28eac4df57 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f28eac12abb in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f28eacf2158 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10::cuda::SetDevice(int) + 0x3d (0x7f28eacf278d in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #4: std::_Sp_counted_ptr_inplace<std::vector<at::cuda::CUDAEvent, std::allocator<at::cuda::CUDAEvent> >, std::allocator<std::vector<at::cuda::CUDAEvent, std::allocator<at::cuda::CUDAEvent> > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() + 0x9a (0x7f28ebefb0ea in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x3b0 (0x7f28ebec8b30 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x20a (0x7f28ebedc82a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x75 (0x7f28ebedcaa5 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0xd6de4 (0x7f2942e3fde4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #9: <unknown function> + 0x8609 (0x7f2962754609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #10: clone + 0x43 (0x7f296288e133 in /usr/lib/x86_64-linux-gnu/libc.so.6)

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 2 (pid: 113) of binary: /usr/bin/python3.10

**Comment by quantumiracle** [comment]
Hi, 

Same issue here. Is this problem solved?
