### ISSUE TITLE
[BUG]: Example GPT Titans CUDA Runtime Error with Default Pip Requirements

### ISSUE THREAD

**Issue by JThh** [hpcaitech/ColossalAI#3733]
### 🐛 Describe the bug

When running the example in the [folder](https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/gpt/titans), an error will occur with the traces shown below. The environment settings are as in the requirements.txt, `colossalai====0.2.0+torch1.12cu11.3`, `torch==1.12.1`, and `titans==0.0.7`. 

It is worth mentioning that there is a warning message at my torch CUDA __init__ file, before the error: 

```
NVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100 80GB PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

```

Here are the error traces.

```
Traceback (most recent call last):
  File "train_gpt.py", line 113, in <module>
    main()
  File "train_gpt.py", line 38, in main
    colossalai.launch_from_torch(config=args.config)
  File "/home/lchjt/.local/lib/python3.8/site-packages/colossalai/initialize.py", line 220, in launch_from_torch
    launch(config=config,
  File "/home/lchjt/.local/lib/python3.8/site-packages/colossalai/initialize.py", line 111, in launch
    gpc.detect_num_processes_on_current_node()
  File "/home/lchjt/.local/lib/python3.8/site-packages/colossalai/context/parallel_context.py", line 91, in detect_num_processes_on_current_node
    dist.all_gather_object(hostname_list, hostname, group=self.get_group(ParallelMode.GLOBAL))
  File "/home/lchjt/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1650, in all_gather_object
    object_sizes_tensor = torch.zeros(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
```

**Comment by JThh** [comment]
Turned out it was due to a mismatch of torch version with cuda version.

**Comment by stephankoe** [comment]
I have had this issue with ColossalAI 0.2.0 on an A100 and V100 machine when I installed torch with `conda`. Using `pip` instead solved this problem for me:

```bash
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 --trusted-host=download.pytorch.org
```
